works: true

spring:
 datasource:
  fortunes:
   1: A dubious friend may be an enemy in camouflage.
   2: A person of words and not deeds is like a garden full of weeds.
   3: A smile is your personal welcome mat.
   4: Believe in yourself and others will too.
   5: Carve your name on your heart and not on marble.
   6: Curiosity kills boredom. Nothing can kill curiosity.
   7: Distance yourself from the vain.
   8: Don’t let the past and useless detail choke your existence.
   9: Everyday in your life is a special occasion.
   10: It is worth reviewing some old lessons.
   11: Listen not to vain words of empty tongue.
   12: Nothing is more difficult, and therefore more precious, than to be able to decide.
   13: Now is a good time to buy stock.
   14: Perhaps you’ve been focusing too much on saving.
